<?xml version="1.0" encoding="utf-8"?><Database Name="aspnet-MvcApplication1-20141222224613" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\aspnet-MvcApplication1-20141222224613.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="aspnet_MvcApplication1_20141222224613ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Documents" Member="Documents">
    <Type Name="Documents">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsInRecycle" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Project" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Association Name="Project_Document" Member="Projects" ThisKey="Project" OtherKey="Id" Type="Projects" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Projects" Member="Projects">
    <Type Name="Projects">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserLogin" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Settings" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Project_Document" Member="Documents" ThisKey="Id" OtherKey="Project" Type="Documents" />
      <Association Name="UserProfile_Project" Member="UserProfile" ThisKey="UserLogin" OtherKey="Login" Type="UserProfile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PriorityLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LevelName" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Association Name="Role_UserProfile" Member="UserProfiles" ThisKey="Id" OtherKey="Role" Type="UserProfile" />
    </Type>
  </Table>
  <Table Name="dbo.SecretQuestions" Member="SecretQuestions">
    <Type Name="SecretQuestion">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Question" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="SecretQuestion_UserProfile" Member="UserProfiles" ThisKey="Id" OtherKey="SecretQuestion" Type="UserProfile" />
    </Type>
  </Table>
  <Table Name="dbo.UserProfile" Member="UserProfiles">
    <Type Name="UserProfile">
      <Column Name="Login" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SecretQuestion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SecretAnswer" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Age" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="Role" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="UserProfile_Project" Member="Projects" ThisKey="Login" OtherKey="UserLogin" Type="Projects" />
      <Association Name="SecretQuestion_UserProfile" Member="SecretQuestion1" ThisKey="SecretQuestion" OtherKey="Id" Type="SecretQuestion" IsForeignKey="true" />
      <Association Name="Role_UserProfile" Member="Role1" ThisKey="Role" OtherKey="Id" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
</Database>