//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id { get; set; }
        public string Path { get; set; }
        public string IsInRecycle { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public int Project { get; set; }
        public string Description { get; set; }
    
        public virtual Projects Project1 { get; set; }
    }
}
