//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecretQuestion
    {
        public SecretQuestion()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int Id { get; set; }
        public string Question { get; set; }
    
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
