//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Projects = new HashSet<Projects>();
        }
    
        public string Login { get; set; }
        public string Mail { get; set; }
        public string Password { get; set; }
        public Nullable<int> SecretQuestion { get; set; }
        public string SecretAnswer { get; set; }
        public Nullable<System.DateTime> Age { get; set; }
        public string FullName { get; set; }
        public int Role { get; set; }
        public byte[] Avatar { get; set; }
    
        public virtual ICollection<Projects> Projects { get; set; }
        public virtual Role Role1 { get; set; }
        public virtual SecretQuestion SecretQuestion1 { get; set; }
    }
}
